name: "CI"

on:
  pull_request:
    types: [opened, synchronize, edited, closed]
  push:
    branches:
      - master

jobs:
  cancel-previous-run:
    name: Cancel previous actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-node
      - run: npm run lint
        working-directory: ./gh-projects/assign-to-project

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-node

      - name: Install dependencies
        run: npm install
        working-directory: ./gh-projects/assign-to-project

      - name: Run tests
        run: npm run test
        working-directory: ./gh-projects/assign-to-project